### ISSUE TITLE
During handling of the above exception, another exception occurred -error

### ISSUE THREAD

**Issue by arun-taiger** [guillaumegenthial/api_ner#1]
When I tried to execute python app.py, I get following error message.

Traceback (most recent call last):
  File "/Users/admin/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/Users/admin/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/Users/admin/anaconda/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/Users/admin/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Key bi-lstm/bidirectional_rnn/bw/lstm_cell/biases not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

**Comment by guillaumegenthial** [comment]
It seems like you're experiencing an issue with weights reloading... Have you deleted the weights somehow? Maybe your OS requires a different paths for the weights / your python/tf install is kind of broken :( 
In case that helps, my environment is
Python 3.6.4
`backports.weakref==1.0.post1
bleach==1.5.0
click==6.7
enum34==1.1.6
Flask==0.12.2
Flask-Cors==3.0.3
funcsigs==1.0.2
futures==3.2.0
gunicorn==19.7.1
html5lib==0.9999999
itsdangerous==0.24
Jinja2==2.10
Markdown==2.6.10
MarkupSafe==1.0
mock==2.0.0
numpy==1.13.3
pbr==3.1.1
protobuf==3.5.1
scipy==1.0.0
six==1.11.0
tensorflow==1.4.1
tensorflow-tensorboard==0.4.0rc3
Werkzeug==0.14.1
`

**Comment by arun-taiger** [comment]
I am using Mac. The weights are there in the correspond directory.  I am using python 3.6. Let me check with  Python 3.6.4  and corresponding config.
